### ISSUE TITLE
I seem to get a CSS issue 

### ISSUE THREAD

**Issue by khushalhirani** [dneukirchen/mod_google_calendar#3]
The message I get is:

' }, header: { left: 'prev,next today', center: 'title', right: 'month,agendaWeek,agendaDay' }, timeFormat: 'H:mm', eventClick: function (event) { window.open(event.url, 'gcalevent', 'width=700,height=600'); return false; }, loading: function (bool) { $('#loading').toggle(bool); } }); });

**Comment by dneukirchen** [comment]
hey @khushalhirani. Thx for reporting. 
Can you specify the issue? When does it occur?

**Comment by khushalhirani** [comment]
The issue occurrea when I change the view to “calendar”. When it’s on list view it’s fine

**Comment by dneukirchen** [comment]
Ok, and what exactly is the issue? Do you see an error in the browser console? Which joomla version are you using? Which browser? Thx.

**Comment by khushalhirani** [comment]
Joomla 3.8 and latest version of Chrome.

The error on console is:

`Uncaught ReferenceError: jQuery is not defined
    at fullcalendar.min.js:6
    at fullcalendar.min.js:6
(anonymous) @ fullcalendar.min.js:6
(anonymous) @ fullcalendar.min.js:6
calendar1:25 GET https://swaminarayan.info//modules/mod_google_calendar/media/fullcalendar/lang/en.js 404 (Not Found)
gcal.js:15 Uncaught ReferenceError: jQuery is not defined
    at gcal.js:15
    at gcal.js:17
(anonymous) @ gcal.js:15
(anonymous) @ gcal.js:17
jquery-migrate.min.js?42a82991457a33f8da1fcb01663280bf:2 JQMIGRATE: Migrate is installed, version 1.4.1
calendar1:59 GET
calendar1:179 Uncaught SyntaxError: Unexpected token <`

**Comment by khushalhirani** [comment]
the link is [https://swaminarayan.info/events/calendar1](url)

**Comment by dneukirchen** [comment]
PLease disable the joomla plugin "System - Email Cloaking" and check again.

**Comment by khushalhirani** [comment]
Disabled it and now I am getting a blank screen. I changed it to default view and the list works so the credentials I added are working but not the calendar view.

Below is the console error

`Uncaught ReferenceError: jQuery is not defined
    at fullcalendar.min.js:6
    at fullcalendar.min.js:6
en.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
gcal.js:15 Uncaught ReferenceError: jQuery is not defined
    at gcal.js:15
    at gcal.js:17
jquery-migrate.min.js?42a82991457a33f8da1fcb01663280bf:2 JQMIGRATE: Migrate is installed, version 1.4.1
calendar1:176 Uncaught TypeError: jQuery(...).fullCalendar is not a function
    at HTMLDocument.<anonymous> (calendar1:176)
    at i (jquery.min.js?42a82991457a33f8da1fcb01663280bf:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?42a82991457a33f8da1fcb01663280bf:2)
    at Function.ready (jquery.min.js?42a82991457a33f8da1fcb01663280bf:2)
    at HTMLDocument.K (jquery.min.js?42a82991457a33f8da1fcb01663280bf:2)`

**Comment by dneukirchen** [comment]
JQuery is loaded after the fullcalender.js
Will fix it in next release.  Thx. for reporting.

**Comment by khushalhirani** [comment]
No worries. Can I do it myself for now?

**Comment by dneukirchen** [comment]
open `modules/mod_google_calendar/tmpl/calendar.php` (or create an template override for the module) and add `JHtml::_('jquery.framework');` in line 2 (before the other script calls). That will force jquery to load before fullcalendar.

**Comment by khushalhirani** [comment]
Thank you. That fixed it
